# Generated by Django 5.0.14 on 2026-04-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('unique_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('loudness', models.FloatField(blank=True, null=True)),
                ('valence', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
