# Generated by Django 6.0.3 on 2026-03-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
