# Generated by Django 6.0.3 on 2026-03-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_external_id_alter_track_bpm_alter_track_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='unique_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
