# Generated by Django 6.0.3 on 2026-04-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='external_id',
        ),
        migrations.AddField(
            model_name='track',
            name='danceability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='loudness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='track',
            name='valence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
