# Generated by Django 6.0.3 on 2026-04-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_remove_track_external_id_track_danceability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
