# Generated by Django 6.0.3 on 2026-04-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        ('tracks', '0004_remove_track_external_id_track_danceability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='song_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='tracks.track'),
        ),
    ]
