from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.test import TestCase

from apps.playlists.domain.spotify_export_service import SpotifyExportService
from apps.playlists.models import Playlist, PlaylistItem
from apps.tracks.models import Track
from apps.tracks.services.track_services import TrackService


User = get_user_model()


class SpotifyExportServiceTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="exportuser",
            email="export@example.com",
            password="testpass123",
        )
        self.playlist = Playlist.objects.create(
            user=self.user,
            title="Road Trip",
            description="For export",
        )
        self.track = Track.objects.create(
            title="Track One",
            artist="Artist One",
            spotify_id="spotify-track-1",
            unique_key="track-one-artist-one",
        )
        PlaylistItem.objects.create(
            playlist=self.playlist,
            track=self.track,
            position=1,
        )

    @patch("apps.playlists.domain.spotify_export_service.SpotifyClient")
    def test_export_uses_track_spotify_ids_and_persists_playlist_id(self, mock_client_cls):
        mock_client = mock_client_cls.return_value
        mock_client.create_playlist.return_value = {"id": "spotify-playlist-123"}

        result = SpotifyExportService.export(
            playlist_id=self.playlist.id,
            access_token="token",
            name="Exported Playlist",
        )

        self.playlist.refresh_from_db()

        mock_client.create_playlist.assert_called_once_with(
            name="Exported Playlist",
            description="Generated by MusicMixxer",
            public=False,
        )
        mock_client.add_tracks_to_playlist.assert_called_once_with(
            "spotify-playlist-123",
            ["spotify-track-1"],
        )
        self.assertEqual(self.playlist.spotify_id, "spotify-playlist-123")
        self.assertEqual(result["spotify_playlist_id"], "spotify-playlist-123")
        self.assertEqual(result["tracks_added"], 1)

    @patch("apps.playlists.domain.spotify_export_service.SpotifyClient")
    def test_export_ignores_playlist_items_without_spotify_track_ids(self, mock_client_cls):
        Track.objects.create(
            title="Track Two",
            artist="Artist Two",
            unique_key="track-two-artist-two",
        )
        PlaylistItem.objects.create(
            playlist=self.playlist,
            track=Track.objects.get(unique_key="track-two-artist-two"),
            position=2,
        )

        mock_client = mock_client_cls.return_value
        mock_client.create_playlist.return_value = {"id": "spotify-playlist-456"}

        result = SpotifyExportService.export(
            playlist_id=self.playlist.id,
            access_token="token",
        )

        mock_client.add_tracks_to_playlist.assert_called_once_with(
            "spotify-playlist-456",
            ["spotify-track-1"],
        )
        self.assertEqual(result["tracks_added"], 1)


class TrackServiceLookupTests(TestCase):
    def test_get_by_unique_key_returns_existing_track(self):
        track = Track.objects.create(
            title="Existing",
            artist="Artist",
            unique_key="existing-artist",
        )

        result = TrackService.get_by_unique_key("existing-artist")

        self.assertEqual(result, track)

    def test_get_by_unique_key_returns_none_for_missing_key(self):
        self.assertIsNone(TrackService.get_by_unique_key("missing-key"))
