from apps.integrations.spotify.client import SpotifyClient
from apps.playlists.models import Playlist
from apps.playlists.models import PlaylistItem


class SpotifyExportService:
    """
    Export DB playlist → Spotify playlist
    """

    @staticmethod
    def export(playlist_id: int, access_token: str, name: str = None):
        client = SpotifyClient(access_token)
        local_playlist = Playlist.objects.get(id=playlist_id)

        # ----------------------------------------
        # 1. Fetch playlist items
        # ----------------------------------------
        items = PlaylistItem.objects.filter(
            playlist_id=playlist_id
        ).select_related("track").order_by("position")

        if not items.exists():
            raise ValueError("Playlist is empty")

        # ----------------------------------------
        # 2. Extract Spotify IDs
        # ----------------------------------------
        track_ids = [
            item.track.spotify_id
            for item in items
            if item.track and item.track.spotify_id
        ]

        if not track_ids:
            raise ValueError("No Spotify tracks available")

        # ----------------------------------------
        # 3. Create Spotify playlist
        # ----------------------------------------
        playlist_name = name or "Organized Playlist"

        spotify_playlist = client.create_playlist(
            name=playlist_name,
            description="Generated by MusicMixxer",
            public=False
        )

        spotify_playlist_id = spotify_playlist.get("id")
        local_playlist.spotify_id = spotify_playlist_id
        local_playlist.save(update_fields=["spotify_id", "updated_at"])

        # ----------------------------------------
        # 4. Add tracks
        # ----------------------------------------
        client.add_tracks_to_playlist(
            spotify_playlist_id,
            track_ids
        )

        return {
            "spotify_playlist_id": spotify_playlist_id,
            "tracks_added": len(track_ids)
        }
